/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.wso2.iot.agent;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author lashan
 */
public class Agent extends javax.swing.JFrame {

    /**
     * Creates new form Agent
     */
    public Agent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupEngineState = new javax.swing.ButtonGroup();
        btnGroupRaining = new javax.swing.ButtonGroup();
        jpnlAlert = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAlerts = new javax.swing.JTable();
        jpnlParameters = new javax.swing.JPanel();
        jlblHumidity = new javax.swing.JLabel();
        jlblSoilMoisture = new javax.swing.JLabel();
        jlblIllumination = new javax.swing.JLabel();
        jlblEngineTemperature = new javax.swing.JLabel();
        jlblTractorSpeed = new javax.swing.JLabel();
        jlblTractorLoad = new javax.swing.JLabel();
        jlblFuelLevel = new javax.swing.JLabel();
        jlblTemperature = new javax.swing.JLabel();
        jlblEngineState = new javax.swing.JLabel();
        spnrTemperature = new javax.swing.JSpinner();
        spnrHumidity = new javax.swing.JSpinner();
        spnrSoilMoisture = new javax.swing.JSpinner();
        spnrIllumination = new javax.swing.JSpinner();
        spnrEngineTemperature = new javax.swing.JSpinner();
        spnrTractorSpeed = new javax.swing.JSpinner();
        spnrTractorLoad = new javax.swing.JSpinner();
        spnrFuelLevel = new javax.swing.JSpinner();
        rbtnStopped = new javax.swing.JRadioButton();
        rbtnRunning = new javax.swing.JRadioButton();
        rbtnIdle = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chkRaining = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spnrInterval = new javax.swing.JSpinner();
        jbtnTrigger = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlAlert.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("ALERTS");

        jtblAlerts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblAlerts);
        if (jtblAlerts.getColumnModel().getColumnCount() > 0) {
            jtblAlerts.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jpnlAlertLayout = new javax.swing.GroupLayout(jpnlAlert);
        jpnlAlert.setLayout(jpnlAlertLayout);
        jpnlAlertLayout.setHorizontalGroup(
            jpnlAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jpnlAlertLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlAlertLayout.setVerticalGroup(
            jpnlAlertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAlertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnlParameters.setBackground(java.awt.Color.lightGray);

        jlblHumidity.setText("Humidity :");

        jlblSoilMoisture.setText("SoilMoisture :");

        jlblIllumination.setText("Illumination :");

        jlblEngineTemperature.setText("Engine Temperature :");

        jlblTractorSpeed.setText("Tractor Speed :");

        jlblTractorLoad.setText(" Tractor Load :");

        jlblFuelLevel.setText("Fuel Level :");

        jlblTemperature.setText("Temperature :");

        jlblEngineState.setText("Engine State :");

        spnrTemperature.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.25d));

        spnrHumidity.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.25d));

        spnrSoilMoisture.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.25d));

        spnrIllumination.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.25d));

        spnrEngineTemperature.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.25d));

        spnrTractorSpeed.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.25d));

        spnrTractorLoad.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.25d));

        spnrFuelLevel.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 100.0d, 0.25d));

        btnGroupEngineState.add(rbtnStopped);
        rbtnStopped.setText("Stopped");
        rbtnStopped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnStoppedActionPerformed(evt);
            }
        });

        btnGroupEngineState.add(rbtnRunning);
        rbtnRunning.setText("Running");
        rbtnRunning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRunningActionPerformed(evt);
            }
        });

        btnGroupEngineState.add(rbtnIdle);
        rbtnIdle.setText("Idle");
        rbtnIdle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIdleActionPerformed(evt);
            }
        });

        jLabel4.setText("C");

        jLabel5.setText("%");

        jLabel6.setText("%");

        jLabel8.setText("%");

        jLabel9.setText("C");

        jLabel10.setText("%");

        jLabel12.setText("mph");

        jLabel13.setText("candela");

        jLabel7.setText("Raining :");

        btnGroupRaining.add(chkRaining);
        chkRaining.setText("true");
        chkRaining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRainingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlParametersLayout = new javax.swing.GroupLayout(jpnlParameters);
        jpnlParameters.setLayout(jpnlParametersLayout);
        jpnlParametersLayout.setHorizontalGroup(
            jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlParametersLayout.createSequentialGroup()
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jlblTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spnrTemperature)
                            .addComponent(chkRaining)
                            .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(spnrTractorSpeed)
                                .addComponent(spnrIllumination)
                                .addComponent(spnrFuelLevel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74))
                    .addGroup(jpnlParametersLayout.createSequentialGroup()
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addComponent(jlblIllumination, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel13))
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addComponent(jlblTractorSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel12))
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addComponent(jlblFuelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel5))
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addComponent(jlblEngineState, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 85, 85)
                                .addComponent(rbtnStopped)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlParametersLayout.createSequentialGroup()
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlblTractorLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblSoilMoisture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblEngineTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblHumidity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnrHumidity)
                            .addGroup(jpnlParametersLayout.createSequentialGroup()
                                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnrEngineTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnrSoilMoisture, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnrTractorLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(14, 14, 14))
                    .addGroup(jpnlParametersLayout.createSequentialGroup()
                        .addComponent(rbtnRunning)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnIdle)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpnlParametersLayout.setVerticalGroup(
            jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParametersLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTemperature)
                    .addComponent(spnrTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblHumidity)
                    .addComponent(spnrHumidity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSoilMoisture)
                    .addComponent(spnrSoilMoisture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblIllumination)
                    .addComponent(spnrIllumination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEngineTemperature)
                    .addComponent(spnrEngineTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTractorSpeed)
                    .addComponent(spnrTractorSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTractorLoad)
                    .addComponent(spnrTractorLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblFuelLevel)
                    .addComponent(spnrFuelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkRaining))
                .addGap(16, 16, 16)
                .addGroup(jpnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblEngineState)
                    .addComponent(rbtnStopped)
                    .addComponent(rbtnRunning)
                    .addComponent(rbtnIdle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(184, 222, 179));

        jLabel3.setText("Data Push Interval :");

        spnrInterval.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jbtnTrigger.setText("Trigger");
        jbtnTrigger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTriggerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(spnrInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnTrigger)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnrInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTrigger))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("agent version 1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlParameters, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlAlert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlAlert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnRunningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRunningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnRunningActionPerformed

    private void rbtnIdleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIdleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIdleActionPerformed

    private void jbtnTriggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTriggerActionPerformed
        // TODO add your handling code here:
        double temperature=(double)spnrTemperature.getValue();
        double humidity=(double)spnrHumidity.getValue();
        double illumination=(double)spnrIllumination.getValue();
        double fuelLevel=(double)spnrFuelLevel.getValue();
        double soilMoisture=(double)spnrSoilMoisture.getValue();
        double tractorLoad=(double)spnrTractorLoad.getValue();
        double tractorSpeed=(double)spnrTractorSpeed.getValue();
        double engineTemp=(double)spnrEngineTemperature.getValue();
        boolean raining = chkRaining.isSelected();
        int interval=(int)spnrInterval.getValue();
        jLabel1.setText("int"+interval);
        if (rbtnRunning.isSelected()){
                 jLabel1.setText("temperature1");
         }
         if (rbtnStopped.isSelected()){
                 jLabel1.setText("temperature2");
         }
         if (rbtnIdle.isSelected()){
                 jLabel1.setText("temperature3");
          }
         
     DefaultTableModel model = (DefaultTableModel)jtblAlerts.getModel();
     model.setValueAt("raining "+raining, 0, 0);//first row
     model.setValueAt("temperature"+temperature, 1, 0);
     model.setValueAt("humidity"+humidity, 2, 0);
     model.setValueAt("illumination"+illumination, 3, 0);
     model.setValueAt("enginetemp"+engineTemp, 4, 0);

   
        
    }//GEN-LAST:event_jbtnTriggerActionPerformed

    private void chkRainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRainingActionPerformed

    private void rbtnStoppedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnStoppedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnStoppedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupEngineState;
    private javax.swing.ButtonGroup btnGroupRaining;
    private javax.swing.JCheckBox chkRaining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton jbtnTrigger;
    private javax.swing.JLabel jlblEngineState;
    private javax.swing.JLabel jlblEngineTemperature;
    private javax.swing.JLabel jlblFuelLevel;
    private javax.swing.JLabel jlblHumidity;
    private javax.swing.JLabel jlblIllumination;
    private javax.swing.JLabel jlblSoilMoisture;
    private javax.swing.JLabel jlblTemperature;
    private javax.swing.JLabel jlblTractorLoad;
    private javax.swing.JLabel jlblTractorSpeed;
    private javax.swing.JPanel jpnlAlert;
    private javax.swing.JPanel jpnlParameters;
    private javax.swing.JTable jtblAlerts;
    private javax.swing.JRadioButton rbtnIdle;
    private javax.swing.JRadioButton rbtnRunning;
    private javax.swing.JRadioButton rbtnStopped;
    private javax.swing.JSpinner spnrEngineTemperature;
    private javax.swing.JSpinner spnrFuelLevel;
    private javax.swing.JSpinner spnrHumidity;
    private javax.swing.JSpinner spnrIllumination;
    private javax.swing.JSpinner spnrInterval;
    private javax.swing.JSpinner spnrSoilMoisture;
    private javax.swing.JSpinner spnrTemperature;
    private javax.swing.JSpinner spnrTractorLoad;
    private javax.swing.JSpinner spnrTractorSpeed;
    // End of variables declaration//GEN-END:variables
}
